steps:
  # Paso 1: Despliegue de Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - read_json_from_gcs
      - --region=europe-west1
      - --source=./mi_app
      - --trigger-bucket=mibucketdeporlatarde
      - --runtime=python39
      - --allow-unauthenticated

  # Paso 2: Construcción de la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/miimagenfinal', '.']

  # Paso 3: Subida de la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/miregistrofinal/miimagenfinal'

  # Paso 4: Despliegue en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'miserviciofinal'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/miregistrofinal/miimagenfinal'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
