steps:
  # Paso 1: Despliegue de Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - read_json_from_gcs
      - --region=europe-west1
      - --source=./mi_app
      - --trigger-bucket=gs://mibucketdeporlatarde
      - --runtime=python39
      - --allow-unauthenticated

  # Paso 2: Construcción de la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/singular-skill-404011/misimageneseloy/miimagenfinal', '.']
      - ./mi_app

  # Paso 3: Subida de la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/singular-skill-404011/misimageneseloy/miimagenfinal

  # Paso 4: Despliegue en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - miserviciofinal
      - --image=europe-west1-docker.pkg.dev/singular-skill-404011/misimageneseloy/miimagenfinal
      - --platform=managed
      - --region=europe-west1
      - --allow-unauthenticated
      - --port=8080
images:
- europe-west1-docker.pkg.dev/singular-skill-404011/misimageneseloy/miimagenfinal